#!/bin/bash
# Auto-generated by /harness-init on 2025-12-06
set -e

echo "========================================="
echo "Initializing BeaconTower.Events environment"
echo "========================================="

echo "Restoring dependencies..."
dotnet restore

echo "Building solution..."
dotnet build --no-restore

echo "Running tests..."
dotnet test --no-build

echo "========================================="
echo "Environment ready!"
echo "========================================="
